# Github-Issue-to-Hexo-source.yml
# github.com/shenjuexiao
# 20260710
# 20260729

# https://github.com/flytam/blog/issues/27
# issue 新增或者修改时触发工作流
# 拉取 hexo 源文件
# 将 issue 生成 hexo 源文件并输出到 hexo 源文件 blog-source 仓库的文章目录下并提交到 blog-source 仓库

name: Deploy Hexo Static Page

env:
  # blog 部署的页面
  BLOG: shenjuexiao/issues-public

on:
  push:
    branches:    
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout hexo source
        uses: action/checkout@v3
        with:
          persist-credentials: 'false'
          ref: 'main'
          token: ${{ secrets.ISSUES_PUBLIC }}
          
      - name: deploy hexo
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PUBLISH_REPOSITORY: ${{ env.BLOG }}
          BRANCH: gh-pages
          PUBLISH_DIR: ./public
          PERSONAL_TOKEN: ${{ secrets.ISSUES_PUBLIC }} 