# 20260710
# https://github.com/flytam/blog/issues/27
# issue 新增或者修改时触发工作流
# 拉取 hexo 源文件
# 将 issue 生成 hexo 源文件并输出到 hexo 源文件 blog-source 仓库的文章目录下并提交到 blog-source 仓库

name: Deploy blog

env:
  # hexo 源文件仓库
  BLOG_SOURCE: shenjuexiao/hexo-source
  # issue 链接
  ISSUE_URL: https://github.com/shenjuexiao/shenjuexiao.github.io/issues
  # blog 部署的页面
  BLOG: shenjuexiao/shenjuexiao.github.io
  # ${{ github.event.issue.user.login }}

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    # 仓库作者才能触发
    if: ${{ github.actor == github.repository_owner }}
    steps:
      - name: Pull Hexo source files
        uses: actions/checkout@v3
        with:
          persist-credentials: 'false'
          repository: ${{ env.BLOG_SOURCE }}
          ref: 'main'
          token: ${{ secrets.Hexo }}
      - name: issue genrate hexo posts
        # uses: flytam/github-issue-to-hexo@v1.0.3
        # 20260710
        uses: flytam/github-issue-to-hexo@v1.0.3
        with:
          issue_url: https://github.com/shenjuexiao/shenjuexiao.github.io/issues
          # 20260710
          # 使用触发的具体 issue
          # issue_url: ${{ github.event.issue.html_url || format('https://github.com/{0}/issues/{1}', github.repository, github.event.inputs.issue_number) }}
          output: 'source/_posts'
          replace: true
          token: ${{ secrets.Hexo }}
      - name: commit hexo source files
        run: |
          echo $(date) > update.md
          git add .
          git config user.name "issue-to-hexo bot"
          git config user.email "shenjuexiao@qq.com"
          git commit -m "Add a post"
      - name: push hexo source files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.Hexo }}
          repository: ${{ env.BLOG_SOURCE }}