# hexo-public-github-cn.yml
# github.com/shenjuexiao
# 2026-07-25

# hexo.io/zh-cn/docs/github-pages
# 在 GitHub Pages 上部署 Hexo

# .github/workflows/pages.yml
name: Pages

on:
  push:
    # default branch
    branches: main
      # 20260725
      # 允许你从 Actions 选项卡手动运行此工作流程
      workflow_dispatch:

# 20260725
# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 20260725
# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false
  
jobs:
  # 20260725
  # 构建工作 + 部署工作 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, 
          # please see: https://github.com/actions/checkout
          # submodules: recursive
          
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: "20"
          
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
            
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      
      # 20260725      
      # 部署到外部仓库
      - name: Deploy to target repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          # GitHub 自动注入 GITHUB_TOKEN
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # 源仓库 Secrets 设置 PERSONAL_TOKEN
          personal_token: ${{ secrets.HEXO_PUBLIC }}
          # 部署仓库（用户名/仓库）
          external_repository: shenjuexiao/hexo-public
          # 部署分支（默认 gh-pages）
          publish_branch: gh-pages
          # 部署文件夹（构建产物目录 Astro / VitePress 默认输出 dist）
          publish_dir: .vitepress/dist
          # 保留历史提交记录（可选）
          keep_files: false
          # 部署强制推送
          force_orphan: false
          # 提交信息（可选）
          commit_message: "Deploy Hexo site - ${{ github.sha }}"
          # 允许外部用户提交（可选，公共仓库建议设为 true）
          allow_empty_commit: false
          # 自定义域名（可选，如果你的站点使用自定义域名）
          # cname: www.example.com
          # 用户信息
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          